name: mobile
description: A new Flutter project for job application tracking.
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  dio: ^5.4.3+1
  shared_preferences: ^2.2.2
  flutter_hooks: ^0.20.5
  flutter_easyloading: ^3.0.5
  google_fonts: ^6.2.1
  forui: ^0.14.0 